### ISSUE TITLE
no running container in `docker ps` after hyper started the pod

### ISSUE THREAD

**Issue by henrysher** [hyperhq/hyper#11]
```pod.json
{
    "name": "myweb",
    "containers" : [{
        "image": "httpd",
        "ports": [{
            "containerPort": 80,
            "hostPort": 8080
        }]
    }],
    "resource": {
        "vcpu": 1,
        "memory": 512
    }
}
```
```
root@debian:~# hyper run -p pod-1 
POD id is pod-WXBmlQWfEf
Time to run a POD is 4577 ms
```
```
But no running container found in `docker ps`.

**Comment by carmark** [comment]
Hello Henry,

Thanks for trying hyper.  You can use `hyper list container` command to check the running containers if you want.
More details regarding with `list` sub-command are following:
```
# hyper list --help
Usage:
  hyper list [pod|container]

list all pods or container information

Help Options:
  -h, --help  Show this help message
```

**Comment by henrysher** [comment]
@carmark thanks, i have got this container via **hyper list container**. One more problem: the running container did not run as a web server, expected in pod file. I have gone through your document, it seems no kind of tips for the troubleshooting. Besides, i have used "hyper exec" and tried to execute some command in my container, but the outuput was nothing. Could you please help me on this problem?

**Comment by gao-feng** [comment]
@henrysher Hi, try to run hyperd manually with  parameter -v=3, this will give you full debug message.

**Comment by henrysher** [comment]
@gao-feng i got the error message, but no idea as the document said, if no tty configured, by default turned on. 
```
[HYPER INFO  0531 20:54:^@55 26892 qemu_process.go] [:53] [console] setup pty device /dev/null for exec
[HYPER INFO  0531 20:54:^@55 26892 qemu_process.go] [:53] [console] ioctl pty device for execcmd failed: Inappropriate ioctl for device
[HYPER INFO  0531 20:54:^@55 26892 qemu_process.go] [:53] [console] setup tty failed
[HYPER INFO  0531 20:54:^@55 26892 qemu_process.go] [:53] [console] hyper send type 10, len 0
[HYPER INFO  0531 20:54:^@55 26892 qemu_process.go] [:53] [console] wait for container started failed
[HYPER INFO  0531 20:54:^@55 26892 qemu_process.go] [:53] [console] container 2e60d916bb16655746830d89e1503c7067ef13560883a6ba62a77f11c44cadc8 init exit code -1
```

**Comment by gao-feng** [comment]
@henrysher Thanks for your helpful information, this is a bug in hyperStart. you can clone hyperStart from https://github.com/hyperhq/hyperstart.git and recompile it, change the Initrd in /etc/hyper/config to the path of hyperStart/build/hyper-initrd.img. 

NOTE: you should use '#' to comment the Cbfs in hyper config too, since the cbfs-qboot.rom doesn't contain new hyper-initrd.img. if you want to use cbfs-qboot.rom, please use cbfstool to generate new cbfs-qboot.rom

#dd if=/dev/zero of=boot.bin bs=4096 count=1
#cbfstool cbfs-qboot.rom create -s 4096k -B boot.bin -m x86  0x1000
#cbfstool cbfs-qboot.rom add -f /prefix/hyperStart/build/kernel -n vmlinuz -t raw
#cbfstool cbfs-qboot.rom add -f /prefix/hyperStart/build/hyper-initrd.img -n initrd -t raw
#echo "console=ttyS0,panic=1" > cmdline
#cbfstool cbfs-qboot.rom add -f cmdline -n cmdline -t raw

**Comment by gao-feng** [comment]
@henrysher the port-map and inspect command are on the way, will come soon. Thanks!

**Comment by gao-feng** [comment]
@henrysher the install script updated too, you can reinstall it by curl -sSL https://hyper.sh/install | bash now. thanks!

**Comment by gnawux** [comment]
looks no further problems, close this issue
